sudo: required
services:
- docker
language: cpp

env:
- P=linux_x86_64 A=cp34m
- P=linux_x86_64 A=cp35m
- P=linux_x86_64 A=cp36m
- P=linux_x86_64 A=cp37m
- P=linux_x86_64 A=cp38
- P=linux_i686 A=cp34m
- P=linux_i686 A=cp35m
- P=linux_i686 A=cp36m
- P=linux_i686 A=cp37m
- P=linux_i686 A=cp38
- P=linux_armv7l A=cp34m
- P=linux_armv7l A=cp35m
- P=linux_armv7l A=cp36m
- P=linux_armv7l A=cp37m
- P=linux_armv7l A=cp38
- P=linux_aarch64 A=cp34m
- P=linux_aarch64 A=cp35m
- P=linux_aarch64 A=cp36m
- P=linux_aarch64 A=cp37m
- P=linux_aarch64 A=cp38

install:
- cd $TRAVIS_BUILD_DIR
- mkdir pylon_installer && cd pylon_installer
- |
  for PYLON_ARCH in armhf arm64 x86 x86_64 ; do
      travis_retry curl -sSfL -O "${PYLON_DOWNLOAD_URL_BASE}pylon-5.2.0.13457-${PYLON_ARCH}.tar.gz"
  done
- echo "Pylon Installer:" && ls

script:
- cd $TRAVIS_BUILD_DIR
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
- "./scripts/build/build-arch.sh --platform-tag $P --abi-tag $A --pylon-dir ./pylon_installer"

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: R46oPGgeRYe2GB5JLMW8doUQf4lQx1oa+Jvr7HMbZpoVHC/EV37l9wrYLkY3BHLc3DUB6Xnc94Dc0IxEnQ3AV+vuSmDTDqdsEo7KYF+ZRMab+J4XpzLvP7E0QHwslXhCIUraEtTom4UydV5Oh6Zz4KA5utNjE9O7KUHHatcccq7/fP/8M2aZocVkkwOzNfl91tTT1nJXMtf10XGKkdI1O0VwSLkXjihIbPDANx53RWCgJgD3JGwbsDQf3lg6mzaJyx7DJ0BVSZT5tErE32pkLJqXNLsy/RQ1lPu0Ycf1HxrgYqH8NvDu4KxfKw41dcMkp6gN4ELhuVOChkztvxB1QPKHn6SdJL86+ipOZiycdnqvAAg1UD2q9idCDE4KhrD8PBJXme/1qLq578NA2PmXbWEGuHk69N/CNWhg898pFUQb600LhpsT28J7HVxGOrELr/6W0RNuEA0YCemfhDm5CQlFw8GVQ4DdFOM6dMyeeQnuWbXKQow9W0ZH/Hf8cklLfvYRYZxoulHzOF6Ley1MMVO2RHWnkZ078Xatm37El2oHkv1xxr/7Yo8GZyKTzaRKrsemtIFnuCxmK/JKGhKJlgtn6en4PL99X4EjmokjL5dhXSgz6jGb72xK7V+Xo5N6DH5t4p5huHXO8HXd5Sq3jHXD5eOZu5iHiwdrkzcJgkc=
  file_glob: true
  file: dist/*
  on:
    repo: basler/pypylon
    branch: master
    tags: true
